services:
  - type: web
    name: atlaspay-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: SERVER_PORT
        value: "8080"
      - key: DB_HOST
        fromDatabase:
          name: atlaspay-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: atlaspay-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: atlaspay-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: atlaspay-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: atlaspay-db
          property: database
      - key: DB_SSLMODE
        value: require
      - key: REDIS_HOST
        fromService:
          name: atlaspay-redis
          property: host
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true

  - type: keyvalue
    name: atlaspay-redis
    plan: free

databases:
  - name: atlaspay-db
    plan: free
    databaseName: atlaspay
    user: atlaspay
